//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(DeriveActiveEnum, EnumIter, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TaskInDayType {
    #[sea_orm(string_value = "TASK")]
    TASK,
    #[sea_orm(string_value = "CUSTOM")]
    CUSTOM,
}
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "TaskInDay")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    #[sea_orm(column_name = "notificationId", column_type = "Text", nullable, unique)]
    pub notification_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub r#type: TaskInDayType,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    #[sea_orm(column_name = "taskId", column_type = "Text", indexed)]
    pub task_id: Uuid,
    #[sea_orm(column_name = "date", indexed)]
    pub date: DateTimeUtc,
    #[sea_orm(column_name = "startTime", indexed)]
    pub start_time: DateTimeUtc,
    #[sea_orm(column_name = "endTime", indexed)]
    pub end_time: DateTimeUtc,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "notification_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub notification: HasOne<super::notification::Entity>,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
