//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(DeriveActiveEnum, EnumIter, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TaskViewType {
    // 手动添加任务引用
    #[sea_orm(string_value = "ALTERNATIVE")]
    ALTERNATIVE,
    // 自动查找任务列表
    #[sea_orm(string_value = "AUTO")]
    AUTO,
}
#[derive(
    DeriveActiveEnum, EnumIter, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Copy,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TaskViewDefineMode {
    // 手动添加任务引用
    #[sea_orm(string_value = "GUI")]
    GUI,
    // 自动查找任务列表
    #[sea_orm(string_value = "SCRIPT")]
    SCRIPT,
}
#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "TaskView")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub r#type: TaskViewType,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_name = "sortOrder", indexed)]
    pub sort_order: i32,
    #[sea_orm(column_name = "defineMode", column_type = "Text")]
    pub define_mode: TaskViewDefineMode,
    #[sea_orm(column_name = "guijsonData", column_type = "Text", nullable)]
    pub guijson_data: Option<String>,
    #[sea_orm(column_name = "autoScript", column_type = "Text", nullable)]
    pub auto_script: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub task_view_tasks: HasMany<super::task_view_task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
