//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::initial_entities::NumberType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "TaskTargetRecord")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub value: NumberType,

    #[sea_orm(column_name = "recordAt")]
    pub record_at: DateTimeUtc,
    #[sea_orm(column_name = "taskId", column_type = "Text", indexed)]
    pub task_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
