//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

pub mod prelude;

pub mod next_task;
pub mod notification;
pub mod report;
pub mod task;
pub mod task_anchor;
pub mod task_group;
pub mod task_in_day;
pub mod task_target_record;
pub mod task_view;
pub mod task_view_task;
