//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use serde::Deserialize;

pub mod prelude;

pub mod next_task;
pub mod notification;
pub mod task;
pub mod task_anchor;
pub mod task_group;
pub mod task_in_day;
pub mod task_target_record;
pub mod task_view;
pub mod task_view_task;

#[derive(Deserialize)]
pub struct OrderModel {
    pub id: String,
    pub sort_order: i32,
}
