//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::utils::option3::{de_option3, Option3};

#[derive(DeriveActiveEnum, EnumIter, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum NextTaskMode {
    #[sea_orm(string_value = "SIMPLE")]
    SIMPLE,
    #[sea_orm(string_value = "COMPLEX")]
    COMPLEX,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "NextTask")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mode: NextTaskMode,
    pub a: i32,
    pub b: i32,
    #[sea_orm(column_name = "endDate")]
    pub end_date: Option<DateTimeUtc>,
    #[sea_orm(column_name = "taskId", column_type = "Text", unique, indexed)]
    pub task_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Deserialize, Serialize, Debug)]
pub struct CreateModel {
    // pub mode: NextTaskMode,
    pub a: i32,
    pub b: i32,
    pub task_id: String,
    pub end_date: Option<String>,
}
#[derive(Deserialize, Serialize, Debug)]
pub struct CreateModelForBatchCreateTask {
    // pub mode: NextTaskMode,
    pub a: i32,
    pub b: i32,
    // pub task_id: String,
    pub end_date: Option<String>,
}

#[derive(Deserialize, Serialize, Debug)]
pub struct UpdateModel {
    pub mode: Option<NextTaskMode>,
    pub a: Option<i32>,
    pub b: Option<i32>,
    #[serde(default, deserialize_with = "de_option3")]
    pub end_date: Option3<String>,
}
