//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "NextTask")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mode: Option<String>,
    pub a: i32,
    pub b: i32,
    #[sea_orm(
        column_name = "endDate",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text",
        nullable
    )]
    pub end_date: Option<String>,
    #[sea_orm(column_name = "taskId", column_type = "Text", unique)]
    pub task_id: String,
    #[sea_orm(
        column_name = "createdAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub created_at: String,
    #[sea_orm(
        column_name = "updatedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub updated_at: String,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Deserialize, Serialize, Debug)]
pub struct CreateModel {
    pub mode: String,
    pub a: i32,
    pub b: i32,
    pub task_id: String,
    pub end_date: Option<String>,
}
