//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Notification")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(
        column_name = "notifyAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub notify_at: String,
    #[sea_orm(
        column_name = "notifiedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text",
        nullable
    )]
    pub notified_at: Option<String>,
    #[sea_orm(
        column_name = "createdAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub created_at: String,
    #[sea_orm(
        column_name = "updatedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub updated_at: String,
    #[sea_orm(has_one)]
    pub task_in_day: HasOne<super::task_in_day::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
