//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

// pub use super::next_task::Entity as NextTask;
pub use super::notification::Entity as Notification;
pub use super::task::Entity as Task;
pub use super::task_anchor::Entity as TaskAnchor;
pub use super::task_group::Entity as TaskGroup;
pub use super::task_in_day::Entity as TaskInDay;
pub use super::task_target_record::Entity as TaskTargetRecord;
pub use super::task_view::Entity as TaskView;
pub use super::task_view_task::Entity as TaskViewTask;
