//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "TaskView")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_name = "sortOrder")]
    pub sort_order: i32,
    #[sea_orm(column_name = "defineMode", column_type = "Text")]
    pub define_mode: String,
    #[sea_orm(column_name = "GUIJSONData", column_type = "Text", nullable)]
    pub guijson_data: Option<String>,
    #[sea_orm(column_name = "autoScript", column_type = "Text", nullable)]
    pub auto_script: Option<String>,
    #[sea_orm(
        column_name = "createdAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub created_at: String,
    #[sea_orm(
        column_name = "updatedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub updated_at: String,
    #[sea_orm(has_many)]
    pub task_view_tasks: HasMany<super::task_view_task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
