//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "TaskAnchor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "sortOrder")]
    pub sort_order: i32,
    #[sea_orm(column_name = "taskId", column_type = "Text", unique)]
    pub task_id: String,
    #[sea_orm(
        column_name = "createdAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub created_at: String,
    #[sea_orm(
        column_name = "updatedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub updated_at: String,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
