//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Task")]
pub struct Model {
    #[sea_orm(column_name = "sortOrder")]
    pub sort_order: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "groupId", column_type = "Text")]
    pub group_id: String,
    #[sea_orm(
        column_name = "createdAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub created_at: String,
    #[sea_orm(
        column_name = "updatedAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text"
    )]
    pub updated_at: String,
    #[sea_orm(
        column_name = "doneAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text",
        nullable
    )]
    pub done_at: Option<String>,
    #[sea_orm(
        column_name = "startAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text",
        nullable
    )]
    pub start_at: Option<String>,
    #[sea_orm(
        column_name = "endAt",
        ignore,
        column_type = "custom(\"DATETIME\")",
        select_as = "text",
        nullable
    )]
    pub end_at: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    pub priority: i32,
    pub factor: i32,
    #[sea_orm(column_name = "parentId", column_type = "Text", nullable)]
    pub parent_id: Option<String>,
    #[sea_orm(column_name = "createIndex")]
    pub create_index: i32,
    #[sea_orm(column_name = "createdByTaskId", column_type = "Text", nullable)]
    pub created_by_task_id: Option<String>,
    pub target: Option<Decimal>,
    #[sea_orm(column_name = "targetType", column_type = "Text", nullable)]
    pub target_type: Option<String>,
    #[sea_orm(has_one)]
    pub next_task: HasOne<super::next_task::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef2",
        from = "created_by_task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub task_2: HasOne<Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef1",
        from = "parent_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task_1: HasOne<Entity>,
    #[sea_orm(has_one)]
    pub task_anchor: HasOne<super::task_anchor::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task_group: HasOne<super::task_group::Entity>,
    #[sea_orm(has_many)]
    pub task_in_days: HasMany<super::task_in_day::Entity>,
    #[sea_orm(has_many)]
    pub task_target_records: HasMany<super::task_target_record::Entity>,
    #[sea_orm(has_many)]
    pub task_view_tasks: HasMany<super::task_view_task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
