//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{
    entities::NumberType,
    utils::option3::{de_option3, Option3},
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "TaskTargetRecord")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    // 使用String的原因是因为原来的数字类型Decimal 在sqlite中非常不准确，小数点会很离谱
    pub value: NumberType,
    // 備注
    #[sea_orm(column_name = "remark", column_type = "Text", nullable)]
    pub remark: Option<String>,
    #[sea_orm(column_name = "recordAt")]
    pub record_at: DateTimeUtc,
    #[sea_orm(column_name = "taskId", column_type = "Text")]
    pub task_id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreateModel {
    pub value: NumberType,
    pub task_id: String,
    pub remark: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct UpdateModel {
    pub value: Option<NumberType>,
    pub record_at: Option<String>,
    #[serde(default, deserialize_with = "de_option3")]
    pub remark: Option3<String>,
}
