//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::entities::task;

#[derive(DeriveActiveEnum, EnumIter, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TaskState {
    #[sea_orm(string_value = "DONE")]
    DONE,
    #[sea_orm(string_value = "UNDONE")]
    UNDONE,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Task")]
pub struct Model {
    #[sea_orm(column_name = "sortOrder", default_value = 0)]
    pub sort_order: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "groupId", column_type = "Text")]
    pub group_id: Uuid,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTimeUtc,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTimeUtc,
    #[sea_orm(column_name = "doneAt")]
    pub done_at: Option<DateTimeUtc>,
    #[sea_orm(column_name = "startAt")]
    pub start_at: Option<DateTimeUtc>,
    #[sea_orm(column_name = "endAt")]
    pub end_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<TaskState>,
    #[sea_orm(default_value = 25)]
    pub priority: i32,
    #[sea_orm(default_value = 1)]
    pub factor: i32,
    #[sea_orm(column_name = "parentId", column_type = "Text", nullable)]
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_name = "createIndex", default_value = 0)]
    pub create_index: i32,
    #[sea_orm(column_name = "createdByTaskId", column_type = "Text", nullable)]
    pub created_by_task_id: Option<Uuid>,
    pub target: Option<Decimal>,
    #[sea_orm(column_name = "targetType", column_type = "Text", nullable)]
    pub target_type: Option<String>,
    #[sea_orm(has_one)]
    pub next_task: HasOne<super::next_task::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef2",
        from = "created_by_task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub created_by_task: HasOne<Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef1",
        from = "parent_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub parent: HasOne<Entity>,
    #[sea_orm(has_one)]
    pub task_anchor: HasOne<super::task_anchor::Entity>,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task_group: HasOne<super::task_group::Entity>,
    #[sea_orm(has_many)]
    pub task_in_days: HasMany<super::task_in_day::Entity>,
    #[sea_orm(has_many)]
    pub task_target_records: HasMany<super::task_target_record::Entity>,
    #[sea_orm(has_many)]
    pub task_view_tasks: HasMany<super::task_view_task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Deserialize, Serialize)]
pub struct CreateModel {
    pub content: String,
    pub group_id: String,
    pub create_index: Option<i32>,
    pub priority: Option<i32>,
    pub factor: Option<i32>,
    pub description: Option<String>,
    pub parent_id: Option<String>,
    pub state: Option<TaskState>,
    pub target: Option<Decimal>,
    pub target_type: Option<String>,
    pub start_at: Option<String>,
    pub end_at: Option<String>,
    pub done_at: Option<String>,
    pub created_by_task_id: Option<String>,
}

// export type BatchCreateTask = {
//   task: Partial<
//     Omit<
//       Task,
//       | "state"
//       | "id"
//       | "children"
//       | "nextTask"
//       | "createdAt"
//       | "updatedAt"
//       | "taskViewTasks"
//     >
//   > &
//     Required<Pick<Task, TaskRequiredKeys>>
//   nextTask?: Omit<NextTask, "taskId" | "id" | "createdAt" | "updatedAt">
//   children?: BatchCreateTask[]
// }

#[derive(Debug, Deserialize, Serialize)]
pub struct BatchCreateTaskModel {
    pub task: CreateModel,
    pub next_task: Option<super::next_task::CreateModel>,
    pub children: Option<Vec<BatchCreateTaskModel>>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct UpdateModel {
    pub id: Option<String>,
    pub content: Option<String>,
    pub group_id: Option<String>,
    pub create_index: Option<i32>,
    pub priority: Option<i32>,
    pub factor: Option<i32>,
    pub description: Option<Option<String>>,
    pub parent_id: Option<Option<String>>,
    pub state: Option<Option<TaskState>>,
    pub target: Option<Option<Decimal>>,
    pub target_type: Option<Option<String>>,
    pub start_at: Option<Option<String>>,
    pub end_at: Option<Option<String>>,
    pub done_at: Option<Option<String>>,
    pub created_by_task_id: Option<Option<String>>,
}

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct BatchEditTasksResult {
    pub created: Vec<task::Model>,
    pub updated: Vec<task::Model>,
}
